baseurl                 = "https://rtrenneman.github.io/"
languageCode            = "en-us"
title                   = "My Website"
theme                   = "hugo-phlat-theme"

[permalinks]
    post                = "/:year/:month/:slug/"
    page                = "/:slug/"

[taxonomies]
    tag                 = "tags"
    category            = "categories"

# The header menu will appear as an inline-list at the top right of the page
[[menu.header]]
    name                = "Home"
    weight              = 1
    url                 = "/"

[[menu.header]]
    name                = "About"
    weight              = 3
    url                 = "/about/"

# The footer menu will appear as an inline-list at the bottom left of the footer found at the bottom of the screen
[[menu.footer]]
    name                = "Privacy Policy"
    weight              = 1
    url                 = "/privacy-policy/"

[params]
    keywords            = ["default", "keywords", "if", "no", "front", "matter"]
    description         = "A description that will appear as a default if front matter does not exist"


